hostname {env:MADDY_HOSTNAME}

tls file /certs/{env:MADDY_TLS_DOMAIN}/certificate.pem /certs/{env:MADDY_TLS_DOMAIN}/privatekey.pem {
    protocols tls1.2 tls1.3
}

auth.pass_table local_authdb {
    table file /data/auth/smtp_passwd
}

submission tcp://0.0.0.0:587 tls://0.0.0.0:465 {
    hostname {env:MADDY_HOSTNAME}
    tls file /certs/{env:MADDY_TLS_DOMAIN}/certificate.pem /certs/{env:MADDY_TLS_DOMAIN}/privatekey.pem {
        protocols tls1.2 tls1.3
    }
    auth &local_authdb
    sasl_login yes
    max_message_size {env:MADDY_MAX_MESSAGE_SIZE}

    limits {
        all rate {env:MADDY_SUBMISSION_RATE_LIMIT}
        all concurrency {env:MADDY_SUBMISSION_CONCURRENCY_LIMIT}
    }

    default_destination {
        deliver_to smtp tcp://{env:MADDY_SES_HOST}:{env:MADDY_SES_PORT} {
            starttls yes
            auth plain "{env:MADDY_SES_USERNAME}" "{env:MADDY_SES_PASSWORD}"
        }
    }
}
